import React, { useState } from 'react';
import { GlassCard } from '../../components/Common/GlassCard';
import { exportService } from '../../services/exportService';
import {
  MOCK_TRANSFORMERS,
  MOCK_OUTAGES,
  MOCK_ANOMALIES,
  MOCK_DASHBOARD_SUMMARY
} from '../../services/mockData';
import {
  FileText,
  Download,
  Printer,
  Calendar,
  Layers,
  CheckCircle2,
  Sparkles,
  Zap
} from 'lucide-react';

export const ReportsPage: React.FC = () => {
  const [selectedReport, setSelectedReport] = useState<'DAILY' | 'WEEKLY' | 'RISK' | 'OUTAGES' | 'ANOMALIES'>('DAILY');
  const [isGenerating, setIsGenerating] = useState(false);

  const reportTypes = [
    {
      id: 'DAILY',
      title: 'Daily Grid Operations Report',
      desc: 'Summary of daily peak demand, 24-hour total energy delivered, active feeder loads, and equipment alarms.',
      icon: Zap
    },
    {
      id: 'WEEKLY',
      title: 'Weekly Reliability & SAIDI/SAIFI Audit',
      desc: 'IEEE standard compliance audit covering System Average Interruption Duration, frequency, and restoration metrics.',
      icon: Layers
    },
    {
      id: 'RISK',
      title: 'Transformer Failure Risk Ranking Dossier',
      desc: 'Complete asset intelligence ranking with thermal winding history, days since oil test, and AI recommendations.',
      icon: FileText
    },
    {
      id: 'OUTAGES',
      title: 'Outage Root Cause & Restoration Log',
      desc: 'Chronological outage events, crew dispatch response durations, and affected consumer counts.',
      icon: FileText
    },
    {
      id: 'ANOMALIES',
      title: 'Energy Theft & Meter Tampering Anomaly Log',
      desc: 'Isolation Forest flagged consumption deviations, unscheduled nighttime spikes, and investigation statuses.',
      icon: Sparkles
    }
  ];

  const handleExportCsv = () => {
    if (selectedReport === 'RISK') {
      const headers = ['Code', 'Name', 'Feeder', 'Zone', 'LoadPct', 'TempC', 'HealthScore', 'RiskScore', 'Status', 'Recommendation'];
      const rows = MOCK_TRANSFORMERS.map((t) => [
        t.code,
        t.name,
        t.feederName,
        t.zone,
        t.utilizationPct,
        t.temperatureC,
        t.healthScore,
        t.riskScore,
        t.status,
        t.aiRecommendation
      ]);
      exportService.downloadCsv('GridSense_Asset_Risk_Report', headers, rows);
    } else if (selectedReport === 'OUTAGES') {
      const headers = ['Code', 'Feeder', 'Zone', 'StartTime', 'EstimatedRestoration', 'Cause', 'AffectedConsumers', 'Priority', 'Status'];
      const rows = MOCK_OUTAGES.map((o) => [
        o.code,
        o.feederName,
        o.zone,
        o.startTime,
        o.estimatedRestorationTime,
        o.cause,
        o.affectedConsumers,
        o.priority,
        o.status
      ]);
      exportService.downloadCsv('GridSense_Outage_Report', headers, rows);
    } else if (selectedReport === 'ANOMALIES') {
      const headers = ['Code', 'Consumer', 'Category', 'Pattern', 'ExpectedKwh', 'ActualKwh', 'DeviationPct', 'Severity', 'Status'];
      const rows = MOCK_ANOMALIES.map((a) => [
        a.code,
        a.consumerName,
        a.consumerCategory,
        a.type,
        a.expectedConsumptionKwh,
        a.actualConsumptionKwh,
        a.deviationPct,
        a.severity,
        a.status
      ]);
      exportService.downloadCsv('GridSense_Anomaly_Report', headers, rows);
    } else {
      const headers = ['Metric', 'Value', 'Status'];
      const rows = [
        ['Current Load', `${MOCK_DASHBOARD_SUMMARY.gridPulse.loadMw} MW`, 'Nominal'],
        ['Peak Demand Today', `${MOCK_DASHBOARD_SUMMARY.gridPulse.peakDemandMw} MW`, 'Projected at 19:30'],
        ['Grid Health Index', `${MOCK_DASHBOARD_SUMMARY.gridPulse.gridHealthPct}%`, 'Stable'],
        ['Active Outages', `${MOCK_DASHBOARD_SUMMARY.gridPulse.activeOutagesCount} Feeders`, 'Restoring'],
        ['Energy Delivered Today', `${MOCK_DASHBOARD_SUMMARY.gridPulse.energyTodayGwh} GWh`, 'On track']
      ];
      exportService.downloadCsv('GridSense_Daily_Operations_Report', headers, rows);
    }
  };

  const handleExportPdf = () => {
    const details = {
      'Report Type': selectedReport,
      'Generated By': 'GridSense AI Operations Dispatcher',
      'Active Substation Nodes': '12 Substations Online (100% capacity ready)',
      'Current System Load': `${MOCK_DASHBOARD_SUMMARY.gridPulse.loadMw} MW`,
      'Predicted Peak Demand': `${MOCK_DASHBOARD_SUMMARY.gridPulse.peakDemandMw} MW @ 19:30`,
      'Composite Health Score': `${MOCK_DASHBOARD_SUMMARY.gridPulse.gridHealthPct}%`,
      'High-Risk Assets Identified': '3 Units (TR-104, TR-202, TR-118)',
      'Active Outage Count': `${MOCK_DASHBOARD_SUMMARY.gridPulse.activeOutagesCount} Feeders (1,431 Consumers Affected)`,
      'AI Recommendation': 'Authorize priority inspection for TR-104 and pre-cool commercial cold storage facilities before 17:00 ramp.'
    };
    exportService.downloadPdfReport(`GridSense AI — ${selectedReport} Operations Audit`, details);
  };

  return (
    <div className="p-4 sm:p-6 lg:p-8 space-y-6 max-w-[1600px] mx-auto w-full">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-2 border-b border-white/5">
        <div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight flex items-center gap-2">
            <FileText className="w-6 h-6 text-cyan-400" />
            <span>Automated Reports & Compliance Export</span>
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Generate and export PDF operational dossiers and structured CSV telemetry sheets for regulatory reporting and shift handoffs.
          </p>
        </div>
      </div>

      {/* Report Types Selector */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {reportTypes.map((r) => {
          const Icon = r.icon;
          const isSelected = selectedReport === r.id;

          return (
            <GlassCard
              key={r.id}
              onClick={() => setSelectedReport(r.id as any)}
              className={`p-5 space-y-3 cursor-pointer transition-all ${
                isSelected
                  ? 'border-cyan-500/50 bg-cyan-950/20 shadow-[0_0_25px_rgba(0,229,255,0.15)]'
                  : 'hover:border-white/20'
              }`}
            >
              <div className="flex items-center justify-between">
                <div className={`p-2.5 rounded-xl ${isSelected ? 'bg-cyan-500 text-black' : 'bg-slate-900 text-cyan-400'}`}>
                  <Icon className="w-5 h-5" />
                </div>
                {isSelected && (
                  <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-cyan-500/20 text-cyan-300 font-bold">
                    SELECTED
                  </span>
                )}
              </div>

              <h3 className="text-sm font-bold text-white">{r.title}</h3>
              <p className="text-xs text-slate-400 leading-relaxed">{r.desc}</p>
            </GlassCard>
          );
        })}
      </div>

      {/* Action Strip & Preview Panel */}
      <GlassCard className="p-6 space-y-6">
        <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-white/10">
          <div>
            <h3 className="text-base font-bold text-white">Generate: {selectedReport} Report</h3>
            <p className="text-xs text-slate-400">All metrics certified against calibrated ML test predictions</p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleExportCsv}
              className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-mono font-bold text-xs flex items-center gap-2 border border-white/10 transition-colors"
            >
              <Download className="w-3.5 h-3.5 text-cyan-400" />
              <span>Download CSV Sheet</span>
            </button>

            <button
              onClick={handleExportPdf}
              className="px-5 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-black font-mono font-extrabold text-xs flex items-center gap-2 transition-all shadow-[0_0_20px_rgba(0,229,255,0.4)]"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / Export PDF Dossier</span>
            </button>
          </div>
        </div>

        {/* Live Report Preview */}
        <div className="p-6 rounded-2xl bg-slate-900/80 border border-white/10 space-y-4 font-mono text-xs">
          <div className="flex items-center justify-between border-b border-white/10 pb-3">
            <div>
              <div className="text-sm font-bold text-white">⚡ GRIDSENSE AI PLATFORM — AUDIT REPORT</div>
              <div className="text-[11px] text-slate-400">TARGET: {selectedReport} OPERATIONS OVERVIEW</div>
            </div>
            <div className="text-right text-[11px] text-slate-400">
              DATE: {new Date().toLocaleDateString()} | STATUS: CONFIDENTIAL
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
            <div className="p-3 rounded-lg bg-slate-800/40 border border-white/5 space-y-1">
              <span className="text-slate-400 uppercase text-[10px]">Peak Demand Load</span>
              <div className="text-base font-bold text-white">97.8 MW @ 19:30</div>
            </div>
            <div className="p-3 rounded-lg bg-slate-800/40 border border-white/5 space-y-1">
              <span className="text-slate-400 uppercase text-[10px]">Grid Stability Index</span>
              <div className="text-base font-bold text-emerald-400">91.4% (Nominal)</div>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-cyan-950/20 border border-cyan-500/20 text-slate-300 font-sans text-xs">
            <strong>Automated Validation Summary:</strong> Telemetry streams verify all 12 substations operating within thermal tolerances. Priority actions assigned to Transformer TR-104 and Feeder F-33 restoration crews.
          </div>
        </div>
      </GlassCard>
    </div>
  );
};
